services:
  - type: web
    name: deepsight-fyp-server
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    plan: free
    rootDir: server