[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.virtualenv",  # Alternative to venv
    "cmake",
    "gcc",
    "gnumake",
    "pkg-config"
]

[phases.install]
cmds = [
    "python -m virtualenv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app:app --host 0.0.0.0 --port $PORT"